name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        qt-version: ["6.7.2"]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake ninja-build qt6-base-dev qt6-tools-dev qt6-l10n-tools

      - name: Configure
        run: |
          cmake -S . -B build -G Ninja -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: |
          cmake --build build --config Release

      - name: Test
        run: |
          ctest --output-on-failure --test-dir build

  copr-build:
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y copr-cli python3-packaging

      - name: Configure COPR credentials
        env:
          COPR_LOGIN: ${{ secrets.COPR_LOGIN }}
          COPR_TOKEN: ${{ secrets.COPR_TOKEN }}
        run: |
          mkdir -p ~/.config
          cat <<EOF > ~/.config/copr
[copr-cli]
login = ${COPR_LOGIN}
token = ${COPR_TOKEN}
EOF

      - name: Create source archive
        run: |
          ./scripts/create-source-tarball.sh ${{ github.ref_name || '0.1.0' }}

      - name: COPR build
        env:
          COPR_PROJECT: ${{ secrets.COPR_PROJECT }}
        run: |
          copr-cli build ${COPR_PROJECT} packaging/fedora/bga.spec
